export enum AGENT_STATE {
  ONLINE = 'ONLINE',
  OFFLINE = 'OFFLINE',
  AWAY = 'AWAY'
}

export enum RESPONSE_TYPES {
  GET_AGENT_STATE = 'GET_AGENT_STATE',
  SET_AGENT_STATE = 'SET_AGENT_STATE',
  GET_BRAND_PROFILE = 'GET_BRAND_PROFILE',
  SUBSCRIBE_EX_CONVERSATIONS = 'SUBSCRIBE_EX_CONVERSATIONS',
  SUBSCRIBE_CLOSED_CONVERSATIONS = 'SUBSCRIBE_CLOSED_CONVERSATIONS',
  EX_CONVERSATION_CHANGE_NOTIFICATION = 'ExConversationChangeNotification',
  QUERY_MESSAGES = 'QUERY_MESSAGES',
  ONLINE_EVENT_DISTRIBUTION = 'ONLINE_EVENT_DISTRIBUTION',
}

export enum UMS_RESPONSE_TYPES {
  STRING_RESPONSE = '.ReqBody$StringResp',
  GET_BRAND_PROFILE = '.ams.brandprofile.GetBrandProfile$Response',
  SUBSCRIBE_EX_CONVERSATIONS = '.ams.aam.SubscribeExConversations$Response',
  EX_CONVERSATION_CHANGE_NOTIFICATION = '.ams.aam.ExConversationChangeNotification',
  QUERY_MESSAGES = '.ams.ms.QueryMessages$Response',
  ONLINE_EVENT_DISTRIBUTION = '.ams.ms.OnlineEventDistribution',
}
