export const allFonts = [
  'inter',
  'Inter-Medium',
  'inter_medium',
  'Inter-SemiBold',
  'inter-thin',
  'Inter-Black',
  'Inter-Bold',
  'Inter-ExtraBold',
  'Inter-ExtraLight',
  'Inter-Light',
  'space-grotesk',
  'SpaceGrotesk-Bold',
  'space_grotesk_bold',
  'SpaceGrotesk-Light',
  'SpaceGrotesk-Medium',
  'space_grotesk',
  'SpaceGrotesk_Bold',
  'SpaceGrotesk_Light',
  'SpaceGrotesk_Medium',
  'space-grotesk-semi-bold',
  '$default-font-text',
  '$default-font-headers',
  'montserrat',
  'dank-mono',
  'dank-mono-italic',
  'fira-code',
  'helvetica-light',
  'Helvetica-Oblique',
  'Helvetica',
  'Helvetica-Bold',
  'Helvetica-Neue-UltraLight',
  'Helvetica Neue bold italic',
  'Helvetica Neue UltraLight',
  'Helvetica-Neue',
  'Helvetica-Neue-bold',
  '1',
  'NotoSansJP-Black.otf',
  'NotoSansJP-Bold',
  'NotoSansJP-Light',
  'NotoSansJP-Medium',
  'NotoSansJP-Regular',
  'NotoSansJP-Thin',
  'Montserrat-Light',
  'Montserrat',
  'Montserrat-Thin',
  'Montserrat-Bold',
  'Montserrat-ExtraLightItalic',
  'Helvetica Neue UltraLight',
  'Helvetica Neue',
  'Helvetica Neue bold',
  'WRESTLEMANIA',
  'riesling',
  'Gatsby',
  'Bristol maver',
  'inter-bold',
  'inter-semibold',
  'inter-medium',
  'inter-light',
  'space-grotesk-bold',
  'space-bold',
  'space-grotesk-light',
  'space-grotesk-medium',
  'space-grotesk-semibold',
  'Space Grotesk, sans-serif',
  'Space Grotesk, Tofu',
  'dank-mono',
  'dank-mono-italic',
  'fira-code',
  'bebasNeue',
  'exo-italic',
  'exo',
  'exo-bold',
  'raleway-italic',
  'raleway',
  'samsung-one',
  'samsung-one-bold',
  'samsung one bold',
  'samsung-sharp-sans-bold'
]

export const fontFamilies = [
  'inter',
  'space-grotesk',
  'montserrat',
  'dank-mono',
  'fira-code',
  'helvetica',
  'Helvetica Neue',
  'NotoSansJP',
  'Montserrat',
  'WRESTLEMANIA',
  'riesling',
  'Gatsby',
  'Bristol maver'
]
